=== oroszpeter97/WO02D7WebXML/WO02D7_1029/WO02D7_orarend.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="OP_orarend">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ora" type="oraTipus" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="oraTipus">
    <xs:sequence>
      <xs:element name="targy" type="xs:string"/>
      <xs:element name="idopont" type="idopontTipus"/>
      <xs:element name="helyszin" type="xs:string"/>
      <xs:element name="oktato" type="xs:string"/>
      <xs:element name="szak" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" use="required"/>
    <xs:attribute name="tipus" type="oraTipusTipus" use="required"/>
  </xs:complexType>

    <xs:simpleType name="oraTipusTipus">
        <xs:restriction base="xs:string">
        <xs:enumeration value="eloadas"/>
        <xs:enumeration value="gyakorlat"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="idopontTipus">
        <xs:sequence>
        <xs:element name="nap" type="napTipus"/>
        <xs:element name="tol" type="idopontOraTipus"/>
        <xs:element name="ig" type="idopontOraTipus"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="napTipus">
        <xs:restriction base="xs:string">
        <xs:enumeration value="Hétfő"/>
        <xs:enumeration value="Kedd"/>
        <xs:enumeration value="Szerda"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idopontOraTipus">
        <xs:restriction base="xs:string">
        <xs:pattern value="([01][0-9]|2[0-3]):[0-5][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== oroszpeter97/WO02D7WebXML/WO02D7_1029/WO02D7_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>
<OP_orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="WO02D7_orarend.xsd">
    <ora id="egy" tipus="eloadas">
        <targy>Web Technológia 1.</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>V. EA.</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="ketto" tipus="eloadas">
        <targy>Valószínűség Számítás</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>XV. EA.</helyszin>
        <oktato>Fegyverneki Sándor</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="harom" tipus="gyakorlat">
        <targy>Web Technológia 1.</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>In/101</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="negy" tipus="eloadas">
        <targy>Mesterséges Intelligencia</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>08:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>XXXII. EA.</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="ot" tipus="gyakorlat">
        <targy>Mesterséges Intelligencia</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>XXXII. EA.</helyszin>
        <oktato>Fazekas Levente Áron</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="hat" tipus="gyakorlat">
        <targy>Valószínűség Számítás</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>A/1 316.</helyszin>
        <oktato>Tóth Norbert</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="het" tipus="eloadas">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>08:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>A/1 310.</helyszin>
        <oktato>Kovács József</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="nyolc" tipus="eloadas">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>In/103</helyszin>
        <oktato>Bednarik László</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="kilenc" tipus="eloadas">
        <targy>Vállalati Információs Rendszerek</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>In/103</helyszin>
        <oktato>Dr. Sasvári Péter László</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
    <ora id="tiz" tipus="gyakorlat">
        <targy>Vállalati Információs Rendszerek</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>18:00</tol>
            <ig>20:00</ig>
        </idopont>
        <helyszin>In/103</helyszin>
        <oktato>Dr. Sasvári Péter László</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>
</OP_orarend>
